require 'rexml/document'
include REXML

require_relative '../../lib/helpers/markdown_helper'
require_relative '../../lib/helpers/string_helper'
require_relative '../../lib/helpers/test_helper'

desc 'Run examples'
task :examples do
  rakefile_dir_path = File.dirname(__FILE__)
  test_dir_path = File.join(
                          rakefile_dir_path,
                          'tests',
  )
  TestHelper.create_app_log_dir('rest_api')
  %w/
        albums
        comments
        photos
        posts
        todos
        users
    /.each do |name|
    test_file_name = format('%s_test.rb', name)
    test_file_path = File.join(
        test_dir_path,
        test_file_name,
    )
    command = format('ruby %s', test_file_path)
    system(command)
  end

end
