rakefile_dir_path = File.dirname(__FILE__)

desc 'Run examples'
task :examples do
  test_file_path = File.join(
                           rakefile_dir_path,
                           'log_examples.rb',
  )
  command = format('ruby %s', test_file_path)
  system(command)
end

namespace :report do

  desc 'Create changes report'
  task :changes do
    report_file_path = File.join(
                                       rakefile_dir_path,
                                       'changes_report.html',
    )
    require_relative '../../lib/changes_report'
    ChangesReport.create_report('log', report_file_path)
  end

end
