require_relative '../../lib/changes_report'

rakefile_dir_path = File.dirname(__FILE__)

namespace :create do

  desc 'Create logs'
  task :logs do
    test_file_path = File.join(
        rakefile_dir_path,
        'example_test.rb',
    )
    command = format('ruby %s', test_file_path)
    system(command)
  end

  desc 'Create Changes Report'
  task :changes_report do
    exe_file_path = File.absolute_path(File.join(
                            rakefile_dir_path,
                            '..',
                            '..',
                            'lib',
                            'changes_report.rb'
    ))
    command = format('ruby -r %s -e "ChangesReport.create_report \'changes_report\'', exe_file_path)
    system(command)
  end

end


